# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/how-long

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          key: how-long-{{ checksum "pom.xml" }}

      - run:
          name: Maven install
          command: mvn clean install

      - store_test_results:
          path: target/surefire-reports

      - save_cache:
          paths:
          - ~/.m2
          key: how-long-{{ checksum "pom.xml" }}
